### PR TITLE
USB PHY power up code

### PR DESCRIPTION
**Pull request by grant-olson**
This powers up the USB port on the BL808 so that it can subsequently be used by Linux. This touches the PDS subsystem and registers, which does a lot, so I don't want to take over those registers in a usb specific linux driver.

With this patch in place I can bring up the USB device on linux to the point where it acts like a host device, with the same limitations seen in the SDK, where some devices work but others don't on the Ox64 or M1S.

### CODE REVIEW

**Comment by Fishwaldo** [comment]
Sorry for the late reply. 

I think as this is only used for the linux side of things, we should just include it in the mailbox component rather than a new component. I don't see anybody would want to use this "outside" of the IRQ forwarding to Linux.

**Comment by grant-olson** [comment]
I was thinking the same thing as I got deeper in to the code. I'll revise
so it's a peripheral in the mailbox like the sd card.

**Comment by Fishwaldo** [comment]
Ok. Probably split it out into a new file as the current one is getting pretty big.

**Comment by grant-olson** [comment]
Okay made the following changes:
1. Move the code to the mailbox, changed terminology from usbphy to usb_peripheral to be consistent with terminology.
2. Removed the config option to enable USB separately. We now assume that if we are IRQ forwarding of course we want the USB peripheral to come up.
3. Added a config option to boot the USB in HOST mode vs DEVICE mode. This sets the OTG Host ID pin which happens at the PDS layer so it's difficult to set in linux.

**Comment by Fishwaldo** [comment]
Thanks!

**Pull request merged**
